<?php

namespace AppBundle\Repository;

/**
 * ImageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
