<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYojuazr\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYojuazr/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYojuazr.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYojuazr\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYojuazr\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Yojuazr',
    'container.build_id' => 'f79afdc6',
    'container.build_time' => 1536698944,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYojuazr');
