<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLtixdag\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLtixdag/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLtixdag.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLtixdag\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerLtixdag\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ltixdag',
    'container.build_id' => '215974ba',
    'container.build_time' => 1529343892,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLtixdag');
